### ISSUE TITLE
Evaluation weights

### ISSUE THREAD

**Issue by GabrielAtudorei** [Outmerge/BmtAerospace-EvaluationsApp#14]
-Manager evaluation which is filled by manager for his employee1 has 85%. On each manager page shoul apear by default the manager evaluations for his employees and the he can only choose who is evaluating a specific employee. 
-Colleagues evaluation which is filled by employee2 and emp3 for emp1. The manager sets who is evaluating emp1, with the possibility to chose from other departments also. For each employee must be set a maximum of 3 Col Evs as 5% each.
- Self Evaluation which is identical with manager evaluation is also default on the employee page but has 0% weight.

![flow](https://cloud.githubusercontent.com/assets/23335875/20927932/4aa3e7dc-bbcc-11e6-9866-30a41a33e60b.jpg)

**Comment by cosminatomei** [comment]
#2
